config_dfa = {
'epsilon': 2.483437226361463e-08,
'lr': 2.6298517958226435e-07,
'dataset': 'mnist',
'num_train': 1000,
'num_test': 1000,
'num_val': 1000,
'no_preprocessing_mnist': False,
'no_val_set': False,
'epochs': 100,
'batch_size': 128,
'lr_fb': 0.1,
'lr_fb_init': 0.1,
'target_stepsize': 0.001,
'optimizer': 'Adam',
'optimizer_fb': 'Adam',
'momentum': 0.0,
'sigma': 0.15,
'forward_wd': 0,
'feedback_wd': 0,
'train_parallel': False,
'normalize_lr': True,
'epochs_fb': 10,
'freeze_forward_weights': False,
'freeze_fb_weights': False,
'freeze_fb_weights_output': False,
'shallow_training': False,
'extra_fb_epochs': 0,
'extra_fb_minibatches': 0,
'only_train_first_layer': False,
'train_only_feedback_parameters': False,
'clip_grad_norm': 1.0,
'grad_deltav_cont': False,
'beta1': 0.99,
'beta2': 0.99,
'beta1_fb': 0.99,
'beta2_fb': 0.99,
'epsilon_fb': 1e-08,
'num_hidden': 3,
'size_hidden': 256,
'size_input': 784,
'size_output': 10,
'hidden_activation': 'tanh',
'output_activation': 'softmax',
'no_bias': False,
'network_type': 'DFA',
'initialization': 'xavier_normal',
'fb_activation': 'linear',
'no_cuda': False,
'random_seed': 42,
'cuda_deterministic': False,
'hpsearch': False,
'multiple_hpsearch': False,
'single_precision': False,
'evaluate': False,
'out_dir': None,
'save_logs': True,
'save_BP_angle': True,
'save_GN_angle': False,
'save_GNT_angle': True,
'save_NDI_angle': False,
'save_norm_r': False,
'save_condition_gn': False,
'save_jac_t_angle': False,
'save_jac_pinv_angle': False,
'gn_damping': 1.0,
'gn_damping_hpsearch': False,
'save_nullspace_norm_ratio': False,
'save_fb_statistics_init': False,
'compute_gn_condition_init': False,
'ndi': False,
'alpha_di': 0.001,
'dt_di': 0.1,
'dt_di_fb': 0.001,
'tmax_di': 300.0,
'tmax_di_fb': 50.0,
'epsilon_di': 0.5,
'reset_K': False,
'initialization_K': 'xavier_normal',
'noise_K': 0.0,
'compare_with_ndi': False,
'learning_rule': 'nonlinear_difference',
'use_initial_activations': False,
'c_homeostatic': -1,
'k_p': 0.0,
'k_p_fb': 0.0,
'inst_system_dynamics': False,
'alpha_fb': 0.5,
'noisy_dynamics': False,
'fb_learning_rule': 'normal_controller',
'inst_transmission': False,
'inst_transmission_fb': True,
'time_constant_ratio': 1.0,
'time_constant_ratio_fb': 0.005,
'apical_time_constant': -1,
'apical_time_constant_fb': 0.5,
'use_homeostatic_wd_fb': False,
'proactive_controller': True,
'efficient_controller': True,
'simulate_layerwise': False,
'make_dynamics_plot': False,
}

config_dfc_ssa = {
'alpha_di': 0.00024658638831547176,
'epsilon': 1.3326841152257578e-08,
'lr': 6.043454783083358e-05,
'dataset': 'mnist',
'num_train': 1000,
'num_test': 1000,
'num_val': 1000,
'no_preprocessing_mnist': False,
'no_val_set': False,
'epochs': 100,
'batch_size': 128,
'lr_fb': 0.1,
'lr_fb_init': 0.1,
'target_stepsize': 0.1,
'optimizer': 'Adam',
'optimizer_fb': 'Adam',
'momentum': 0.0,
'sigma': 0.15,
'forward_wd': 0,
'feedback_wd': 0,
'train_parallel': False,
'normalize_lr': True,
'epochs_fb': 0,
'freeze_forward_weights': False,
'freeze_fb_weights': True,
'freeze_fb_weights_output': False,
'shallow_training': False,
'extra_fb_epochs': 2,
'extra_fb_minibatches': 0,
'only_train_first_layer': False,
'train_only_feedback_parameters': False,
'clip_grad_norm': 1.0,
'grad_deltav_cont': False,
'beta1': 0.99,
'beta2': 0.99,
'beta1_fb': 0.99,
'beta2_fb': 0.99,
'epsilon_fb': 1e-08,
'num_hidden': 3,
'size_hidden': 256,
'size_input': 784,
'size_output': 10,
'hidden_activation': 'tanh',
'output_activation': 'softmax',
'no_bias': False,
'network_type': 'DFC',
'initialization': 'xavier_normal',
'fb_activation': 'tanh',
'no_cuda': False,
'random_seed': 42,
'cuda_deterministic': False,
'hpsearch': False,
'multiple_hpsearch': False,
'single_precision': False,
'evaluate': False,
'out_dir': None,
'save_logs': True,
'save_BP_angle': True,
'save_GN_angle': False,
'save_GNT_angle': True,
'save_NDI_angle': False,
'save_norm_r': True,
'save_condition_gn': True,
'save_jac_t_angle': True,
'save_jac_pinv_angle': True,
'gn_damping': 1.0,
'gn_damping_hpsearch': False,
'save_nullspace_norm_ratio': False,
'save_fb_statistics_init': False,
'compute_gn_condition_init': False,
'ndi': True,
'dt_di': 0.005,
'dt_di_fb': 0.001,
'tmax_di': 300,
'tmax_di_fb': 100,
'epsilon_di': 0.5,
'reset_K': False,
'initialization_K': 'weight_product',
'noise_K': 0.0,
'compare_with_ndi': False,
'learning_rule': 'nonlinear_difference',
'use_initial_activations': False,
'c_homeostatic': -1,
'k_p': 0.0,
'k_p_fb': 0.0,
'inst_system_dynamics': False,
'alpha_fb': 1.0,
'noisy_dynamics': False,
'fb_learning_rule': 'normal_controller',
'inst_transmission': True,
'inst_transmission_fb': True,
'time_constant_ratio': 0.005,
'time_constant_ratio_fb': 0.005,
'apical_time_constant': -1,
'apical_time_constant_fb': 0.1,
'use_homeostatic_wd_fb': False,
'efficient_controller': True,
'proactive_controller': True,
'simulate_layerwise': True,
}

config_dfc_ss = {
'alpha_di': 0.00024658638831547176,
'epsilon': 1.3326841152257578e-08,
'lr': 6.043454783083358e-05,
'dataset': 'mnist',
'num_train': 1000,
'num_test': 1000,
'num_val': 1000,
'no_preprocessing_mnist': False,
'no_val_set': False,
'epochs': 100,
'batch_size': 128,
'lr_fb': 0.1,
'lr_fb_init': 0.1,
'target_stepsize': 0.1,
'optimizer': 'Adam',
'optimizer_fb': 'Adam',
'momentum': 0.0,
'sigma': 0.15,
'forward_wd': 0,
'feedback_wd': 0,
'train_parallel': False,
'normalize_lr': True,
'epochs_fb': 0,
'freeze_forward_weights': False,
'freeze_fb_weights': True,
'freeze_fb_weights_output': False,
'shallow_training': False,
'extra_fb_epochs': 2,
'extra_fb_minibatches': 0,
'only_train_first_layer': False,
'train_only_feedback_parameters': False,
'clip_grad_norm': 1.0,
'grad_deltav_cont': False,
'beta1': 0.99,
'beta2': 0.99,
'beta1_fb': 0.99,
'beta2_fb': 0.99,
'epsilon_fb': 1e-08,
'num_hidden': 3,
'size_hidden': 256,
'size_input': 784,
'size_output': 10,
'hidden_activation': 'tanh',
'output_activation': 'softmax',
'no_bias': False,
'network_type': 'DFC',
'initialization': 'xavier_normal',
'fb_activation': 'tanh',
'no_cuda': False,
'random_seed': 42,
'cuda_deterministic': False,
'hpsearch': False,
'multiple_hpsearch': False,
'single_precision': False,
'evaluate': False,
'out_dir': None,
'save_logs': True,
'save_BP_angle': True,
'save_GN_angle': False,
'save_GNT_angle': True,
'save_NDI_angle': True,
'save_norm_r': True,
'save_condition_gn': True,
'save_jac_t_angle': True,
'save_jac_pinv_angle': True,
'gn_damping': 1.0,
'gn_damping_hpsearch': False,
'save_nullspace_norm_ratio': False,
'save_fb_statistics_init': False,
'compute_gn_condition_init': False,
'ndi': False,
'dt_di': 0.005,
'dt_di_fb': 0.001,
'tmax_di': 1000,
'tmax_di_fb': 100,
'epsilon_di': 0.5,
'reset_K': False,
'initialization_K': 'weight_product',
'noise_K': 0.0,
'compare_with_ndi': False,
'learning_rule': 'nonlinear_difference',
'use_initial_activations': False,
'c_homeostatic': -1,
'k_p': 2.0,
'k_p_fb': 0.0,
'inst_system_dynamics': False,
'alpha_fb': 1.0,
'noisy_dynamics': False,
'fb_learning_rule': 'normal_controller',
'inst_transmission': True,
'inst_transmission_fb': True,
'time_constant_ratio': 0.2,
'time_constant_ratio_fb': 0.005,
'apical_time_constant': -1,
'apical_time_constant_fb': 0.1,
'use_homeostatic_wd_fb': False,
'proactive_controller': True,
'efficient_controller': True,
'simulate_layerwise': True,
'make_dynamics_plot': False,
'include_non_converged_samples': True,
}

config_dfc = {
'alpha_di': 0.00024658638831547176,
'epsilon': 1.3326841152257578e-08,
'lr': 6.043454783083358e-05,
'dataset': 'mnist',
'num_train': 1000,
'num_test': 1000,
'num_val': 1000,
'no_preprocessing_mnist': False,
'no_val_set': False,
'epochs': 100,
'batch_size': 128,
'lr_fb': 0.1,
'lr_fb_init': 0.1,
'target_stepsize': 0.1,
'optimizer': 'Adam',
'optimizer_fb': 'Adam',
'momentum': 0.0,
'sigma': 0.15,
'forward_wd': 0,
'feedback_wd': 0,
'train_parallel': False,
'normalize_lr': True,
'epochs_fb': 0,
'freeze_forward_weights': False,
'freeze_fb_weights': True,
'freeze_fb_weights_output': False,
'shallow_training': False,
'extra_fb_epochs': 2,
'extra_fb_minibatches': 0,
'only_train_first_layer': False,
'train_only_feedback_parameters': False,
'clip_grad_norm': 1.0,
'grad_deltav_cont': True,
'beta1': 0.99,
'beta2': 0.99,
'beta1_fb': 0.99,
'beta2_fb': 0.99,
'epsilon_fb': 1e-08,
'num_hidden': 3,
'size_hidden': 256,
'size_input': 784,
'size_output': 10,
'hidden_activation': 'tanh',
'output_activation': 'softmax',
'no_bias': False,
'network_type': 'DFC',
'initialization': 'xavier_normal',
'fb_activation': 'tanh',
'no_cuda': False,
'random_seed': 42,
'cuda_deterministic': False,
'hpsearch': False,
'multiple_hpsearch': False,
'single_precision': False,
'evaluate': False,
'out_dir': None,
'save_logs': True,
'save_BP_angle': True,
'save_GN_angle': False,
'save_GNT_angle': True,
'save_NDI_angle': True,
'save_norm_r': True,
'save_condition_gn': True,
'save_jac_t_angle': True,
'save_jac_pinv_angle': True,
'gn_damping': 1.0,
'gn_damping_hpsearch': False,
'save_nullspace_norm_ratio': False,
'save_fb_statistics_init': False,
'compute_gn_condition_init': False,
'ndi': False,
'dt_di': 0.005,
'dt_di_fb': 0.001,
'tmax_di': 1000,
'tmax_di_fb': 100,
'epsilon_di': 0.5,
'reset_K': False,
'initialization_K': 'weight_product',
'noise_K': 0.0,
'compare_with_ndi': False,
'learning_rule': 'nonlinear_difference',
'use_initial_activations': False,
'c_homeostatic': -1,
'k_p': 2.0,
'k_p_fb': 0.0,
'inst_system_dynamics': False,
'alpha_fb': 1.0,
'noisy_dynamics': False,
'fb_learning_rule': 'normal_controller',
'inst_transmission': True,
'inst_transmission_fb': True,
'time_constant_ratio': 0.2,
'time_constant_ratio_fb': 0.005,
'apical_time_constant': -1,
'apical_time_constant_fb': 0.1,
'use_homeostatic_wd_fb': False,
'proactive_controller': True,
'efficient_controller': False,
'simulate_layerwise': True,
'make_dynamics_plot': False,
'include_non_converged_samples': True,
}

config_collection = {
'DFA': config_dfa,
'DFC-SSA (fixed)': config_dfc_ssa,
'DFC-SS (fixed)': config_dfc_ss,
'DFC (fixed)': config_dfc,
}

result_keys_DFA = [
'loss_test',
'loss_train',
'bp_angles',
'gnt_angles'
]

result_keys = [
'loss_test',
'loss_train',
'bp_angles',
'gnt_angles',
# 'gn_angles',
'ndi_angles',
'condition_gn_angles',
'condition_gn_angles_init',
'jac_transpose_angles',
'jac_transpose_angles_init',
'jac_pinv_angles',
'jac_pinv_angles_init',
# 'nullspace_relative_norm_angles',
'converged',
'not_converged',
'diverged',
]

statistics_keys = [
'avg_time_per_epoch',
'loss_test_val_best',
'loss_train_best',
'loss_val_best',
'loss_test_best',
'loss_train_last',
'loss_val_last',
'loss_test_last',
'loss_train_last',
'acc_test_val_best',
'acc_train_best',
'acc_val_best',
'acc_test_best',
'epoch_best_loss',
]

config_fixed = {
'log_interval': 50,
'save_df': True,
}